export const BOOKS = [
   [
    {
        "goodread_id": "91",
        "author": "Elizabeth Kaye",
        "title": "Ain't No Tomorrow",
        "isbn": "71387366",
        "isbn13": "9.78E+12",
        "bookformat": "Hardcover",
        "pages": "256",
        "rating": "3.41",
        "reviews": "7",
        "totalratings": "34",
        "price": "5.0",
        "genre": "Sports,Sports,Sports,Basketball",
        "img": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1180127253l/1001856.jpg",
        "link": "https://goodreads.com/book/show/1001856.Ain_t_No_Tomorrow"
    },
    {
        "goodread_id": "92",
        "author": "Ward Rutherford",
        "title": "Celtic Lore",
        "isbn": "",
        "isbn13": "",
        "bookformat": "Paperback",
        "pages": "240",
        "rating": "3.31",
        "reviews": "2",
        "totalratings": "32",
        "price": "4.5",
        "genre": "Nonfiction,Fantasy,Mythology,History,Religion,Paganism,Religion",
        "img": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327283567l/1001860.jpg",
        "link": "https://goodreads.com/book/show/1001860.Celtic_Lore"
    },
    {
        "goodread_id": "93",
        "author": "Peter Carstens",
        "title": "The Queen's People: A Study of Hegemony, Coercion, and Accommodation Among the Okanagan of Canada",
        "isbn": "802068278",
        "isbn13": "9.78E+12",
        "bookformat": "Paperback",
        "pages": "382",
        "rating": "0",
        "reviews": "0",
        "totalratings": "0",
        "price": "3.0",
        "genre": "",
        "img": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1417405162l/10018666.jpg",
        "link": "https://goodreads.com/book/show/10018666-the-queen-s-people"
    },
    {
        "goodread_id": "94",
        "author": "Ralph Ellison,Albert Murray,John F. Callahan",
        "title": "Trading Twelves: The Selected Letters of Ralph Ellison and Albert Murray",
        "isbn": "375708057",
        "isbn13": "9.78E+12",
        "bookformat": "Paperback",
        "pages": "272",
        "rating": "4.03",
        "reviews": "7",
        "totalratings": "79",
        "price": "5.0",
        "genre": "Nonfiction,Literature,Music,Jazz,Cultural,African American",
        "img": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1347013305l/100186.jpg",
        "link": "https://goodreads.com/book/show/100186.Trading_Twelves"
    },
    {
        "goodread_id": "95",
        "author": "Blanche Fisher Wright",
        "title": "The Real Mother Goose",
        "isbn": "590225170",
        "isbn13": "9.78E+12",
        "bookformat": "Hardcover",
        "pages": "128",
        "rating": "4.3",
        "reviews": "347",
        "totalratings": "36456",
        "price": "5.5",
        "genre": "Childrens,Poetry,Childrens,Picture Books,Classics,Fiction,Childrens,Nursery Rhymes,Fantasy,Fantasy,Fairy Tales,Kids,Young Adult",
        "img": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1439507704l/1001896._SX318_.jpg",
        "link": "https://goodreads.com/book/show/1001896.The_Real_Mother_Goose"
    },
    {
        "goodread_id": "96",
        "author": "Judith Flanders",
        "title": "A Circle of Sisters: Alice Kipling, Georgiana Burne Jones, Agnes Poynter, and Louisa Baldwin",
        "isbn": "393052109",
        "isbn13": "9.78E+12",
        "bookformat": "Hardcover",
        "pages": "392",
        "rating": "3.67",
        "reviews": "47",
        "totalratings": "261",
        "price": "4.0",
        "genre": "Biography,History,Nonfiction,Historical,Victorian,Art,Biography Memoir,Art,Art History,Literature,19th Century,European Literature,British Literature,Family",
        "img": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1347673530l/100190.jpg",
        "link": "https://goodreads.com/book/show/100190.A_Circle_of_Sisters"
    },
    {
        "goodread_id": "97",
        "author": "RoxAnn Klugman",
        "title": "The Dividend Growth Investment Strategy: How to Keep Your Retirement Income Doubling Every Five Years",
        "isbn": "806521821",
        "isbn13": "9.78E+12",
        "bookformat": "Hardcover",
        "pages": "290",
        "rating": "4",
        "reviews": "1",
        "totalratings": "13",
        "price": "5.0",
        "genre": "Economics,Finance,Finance,Personal Finance",
        "img": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1347623881l/1001916.jpg",
        "link": "https://goodreads.com/book/show/1001916.The_Dividend_Growth_Investment_Strategy"
    },
    {
        "goodread_id": "98",
        "author": "Lowell Miller",
        "title": "The Single Best Investment: Creating Wealth with Dividend Growth",
        "isbn": "965175081",
        "isbn13": "9.78E+12",
        "bookformat": "Hardcover",
        "pages": "265",
        "rating": "4.01",
        "reviews": "18",
        "totalratings": "207",
        "price": "3.99",
        "genre": "Economics,Finance,Business,Finance,Personal Finance,Nonfiction,Currency,Money",
        "img": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1328862552l/1001917.jpg",
        "link": "https://goodreads.com/book/show/1001917.The_Single_Best_Investment"
    },
    {
        "goodread_id": "99",
        "author": "Eithne Quinn",
        "title": "Nuthin' But a G Thang: The Culture and Commerce of Gangsta Rap",
        "isbn": "231124090",
        "isbn13": "9.78E+12",
        "bookformat": "Paperback",
        "pages": "251",
        "rating": "3.59",
        "reviews": "5",
        "totalratings": "39",
        "price": "5.0",
        "genre": "Music,Music,Hip Hop",
        "img": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348110069l/1001929.jpg",
        "link": "https://goodreads.com/book/show/1001929.Nuthin_But_a_G_Thang"
    },
    {
        "goodread_id": "100",
        "author": "Andy Hoare",
        "title": "Star of Damocles",
        "isbn": "",
        "isbn13": "",
        "bookformat": "Mass Market Paperback",
        "pages": "256",
        "rating": "3.28",
        "reviews": "3",
        "totalratings": "102",
        "price": "5.5",
        "genre": "40k,Science Fiction,Fiction",
        "img": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1348247360l/1001948.jpg",
        "link": "https://goodreads.com/book/show/1001948.Star_of_Damocles"
    }
]
]